=== agerrits/Old-Work/PurchaseRequest/schema/PurchaseRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.solazyme.com/PurchaseRequest" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:vpr="http://www.solazyme.com/PurchaseRequest" attributeFormDefault="unqualified">

    <element name="PurReqMain" type="vpr:PurReqMain"></element>
    
    <element name="PurReqDetail" type="vpr:PurReqDetail"></element>
    
    <element name="PurRequestFull" type="vpr:PurReqFull"></element>
    
    <complexType name="PurReqFull">
    	<sequence>
    		<element name="RFQMain" type="vpr:PurReqMain"></element>
    		<element name="RFQDetail" type="vpr:PurReqDetail"></element>
    	</sequence>
    </complexType>

    <complexType name="PurReqDetail">
    	<sequence>
    		<element name="PRQLineItem" type="vpr:PRQLineItem" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="PurReqMain">
    	<sequence>
    		<element name="PurReqID" type="int"></element>
    		<element name="PurReqName" type="string"></element>
    		<element name="PurUserID" type="string"></element>
    		<element name="PurDep" type="string"></element>
    		<element name="PurVendor" type="string"></element>
    		<element name="PurDateReq" type="date"></element>
    		<element name="Shipping" type="string"></element>
    		<element name="PurSubmit" type="date"></element>
    		<element name="PurTotalQuantPr" type="int"></element>
    		<element name="PurTotalCost" type="float"></element>
    		<element name="PurReason" type="string"></element>
    		<element name="PurComments" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="PRQLineItem">
    	<sequence>
    		<element name="LineItemID" type="int"></element>
    		<element name="PurRequestID" type="int"></element>
    		<element name="PurOrderID" type="int"></element>
    		<element name="LineProductNum" type="string"></element>
    		<element name="Quantity" type="int"></element>
    		<element name="ItemCost" type="float"></element>
    		<element name="TotalCost" type="float"></element>
    		<element name="Description" type="string"></element>
    		<element name="Received" type="boolean"></element>
    	</sequence>
    </complexType>
</schema>

=== agerrits/Old-Work/PurchaseRequest/schema/PurchaseRequestSample02.xml
<?xml version="1.0" encoding="UTF-8"?>
<vpr:PurRequestFull xmlns:vpr="http://www.solazyme.com/PurchaseRequest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.solazyme.com/PurchaseRequest PurchaseRequest.xsd ">
  <vpr:RFQMain>
    <vpr:PurReqID>0</vpr:PurReqID>
    <vpr:PurReqName>vpr:PurReqName</vpr:PurReqName>
    <vpr:PurUserID>vpr:PurUserID</vpr:PurUserID>
    <vpr:PurDep>vpr:PurDep</vpr:PurDep>
    <vpr:PurVendor>vpr:PurVendor</vpr:PurVendor>
    <vpr:PurDateReq>2001-01-01</vpr:PurDateReq>
    <vpr:Shipping>vpr:Shipping</vpr:Shipping>
    <vpr:PurSubmit>2001-01-01</vpr:PurSubmit>
    <vpr:PurTotalQuantPr>0</vpr:PurTotalQuantPr>
    <vpr:PurTotalCost>0.0</vpr:PurTotalCost>
    <vpr:PurReason>vpr:PurReason</vpr:PurReason>
    <vpr:PurComments>vpr:PurComments</vpr:PurComments>
  </vpr:RFQMain>
  <vpr:RFQDetail>
    <vpr:PRQLineItem>
      <vpr:LineItemID>0</vpr:LineItemID>
      <vpr:PurRequestID>0</vpr:PurRequestID>
      <vpr:PurOrderID>0</vpr:PurOrderID>
      <vpr:LineProductNum>vpr:LineProductNum</vpr:LineProductNum>
      <vpr:Quantity>0</vpr:Quantity>
      <vpr:ItemCost>0.0</vpr:ItemCost>
      <vpr:TotalCost>0.0</vpr:TotalCost>
      <vpr:Description>vpr:Description</vpr:Description>
      <vpr:Received>true</vpr:Received>
    </vpr:PRQLineItem>
    <vpr:PRQLineItem>
      <vpr:LineItemID>2</vpr:LineItemID>
      <vpr:PurRequestID>0</vpr:PurRequestID>
      <vpr:PurOrderID>0</vpr:PurOrderID>
      <vpr:LineProductNum>vpr:LineProductNum</vpr:LineProductNum>
      <vpr:Quantity>0</vpr:Quantity>
      <vpr:ItemCost>0.0</vpr:ItemCost>
      <vpr:TotalCost>0.0</vpr:TotalCost>
      <vpr:Description>vpr:Description</vpr:Description>
      <vpr:Received>true</vpr:Received>
    </vpr:PRQLineItem>
  </vpr:RFQDetail>
</vpr:PurRequestFull>
